reisa/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from django.conf.urls import (
#     handler403
# )
from django.conf import settings
from django.conf.urls.static import static


import debug_toolbar

from reisa.views import home


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name="home"),
    url(r'^polizas/', include('polizas.urls', namespace="polizas")),
    url(r'^inventarios/', include('inventario.urls', namespace="inventarios")),
    url(r'^usuarios/', include('usuarios.urls', namespace="usuarios")),
    url(r'^tickets/', include('tickets.urls', namespace="tickets")),
    url(r'^froala_editor/', include('froala_editor.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reisa/tickets/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
	url(r'^$',
		TicketPolizaListView.as_view(),
		name="list"),
	url(r'^create/$',
		TicketPolizaCreateView.as_view(),
		name="create_ticket"),
	url(r'^createby/$',
		crear_ticket_por_encargado,
		name="create_by_encargado"),
	url(r'^detail/(?P<pk>[\d]+)/$',
		TicketPolizaDetailView.as_view(),
		name="detail"),
	url(r'^update/(?P<pk>[\d]+)/$',
		TicketPolizaEditView.as_view(),
		name="update"),
	url(r'^autorizar/(?P<pk>[\d]+)/$',
		autorizar_servicio,
		name="autorizar"),
	url(r'^asignar_soporte/(?P<pk>[\d]+)/$',
		asignar_soporte,
		name="asignar"),
	url(r'^concluir_soporte/(?P<pk>[\d]+)/$',
		concluir_soporte,
		name="concluir"),
	url(r'^autorizar_ticket/(?P<pk>[\d]+)/$',
		autorizar_cobro,
		name="cobro"),
	url(r'^search/',
		buscar_ticket,
		name="search")
]

reisa/tickets/models.py
from django.db import models

from usuarios.models import User
from polizas.models import Poliza
from inventario.models import Equipo
from froala_editor.fields import FroalaField

# Create your models here.
class Ticket(models.Model):
	status = (
		('1', 'Pendiente'),
		('2', 'Asignado'),
		('3', 'Atendido'),
		('4', 'Sin cobro'),
		('5', 'Completado')
	)
	tipo_atencion = (
		('1', 'Remota (TeamViewer)'),
		('2', 'Telefónica'),
		('3', 'Presencial')
	)
	reporte = FroalaField()
	registrado_por = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='%(class)s_ticket_created')
	created_at = models.DateField(auto_now_add=True)
	status = models.CharField(max_length=1, choices=status, default='1')
	fecha_atencion = models.DateField(null=True)
	tipo_de_atencion = models.CharField(max_length=1, choices=tipo_atencion, default='1')
	atendido_por = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='%(class)s_ticket_attended')
	solucion = FroalaField(null=True)
	notas_adicionales = FroalaField(blank=True)
	fecha_programada = models.DateField(null=True)
	hora_aproximada = models.TimeField(null=True)

	def is_complete(self):
		return (self.status == '3' or self.status == '4' or self.status == '5')

	def is_attended(self):
		return self.status == '3'


class TicketConPoliza(Ticket):
	poliza = models.ForeignKey(Poliza, on_delete=models.CASCADE)
	equipo = models.ForeignKey(Equipo, on_delete=models.SET_NULL, null=True)
	autorizacion_cliente = models.BooleanField(default=False)

	class Meta:
		permissions = (("add_soporte", "Can add a soporte user"),
						("list_by_equipo", "Can list tickets by equipo"))

	def __str__(self):
		return "#{0} - {1} - {2}".format(self.id, self.poliza.nombre, self.equipo.id)

reisa/tickets/forms.py
from django.forms import ModelForm, Select
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _

from froala_editor.widgets import FroalaEditor

from .models import TicketConPoliza

class TicketPolizaCreateForm(ModelForm):
	class Meta:
		model = TicketConPoliza
		fields = ['reporte', 'poliza', 'equipo']
		widgets = {
			'poliza': Select(attrs={'class': 'form-control'}),
			'reporte': FroalaEditor(options={
				'placeholderText': 'Detalles de la incidencia'},
				attrs={'class': 'form-control'})
		}

class TicketPolizaCreatebyEncargadoForm(ModelForm):
	class Meta:
		model = TicketConPoliza
		fields = ['reporte', 'equipo']
		widgets = {
			'reporte': FroalaEditor(options={
				'placeholderText': 'Detalles de la incidencia'},
				attrs={'class': 'form-control'})
		}


class TicketPolizaUpdateForm(ModelForm):
	class Meta:
		model = TicketConPoliza
		fields = ['reporte', 'equipo']
		widgets = {
			'reporte': FroalaEditor(options={
				'placeholderText': 'Detalles de la incidencia'},
				attrs={'class': 'form-control'})
		}

class TicketPolizaCloseForm(ModelForm):
	class Meta:
		model = TicketConPoliza
		fields = ['solucion', 'notas_adicionales']
		widgets = {
			'solucion': FroalaEditor(options={
				'placeholderText': 'Detalles de la solución'},
				attrs={'class': 'form-control'}),
			'notas_adicionales': FroalaEditor(options={
				'placeholderText': 'Notas Adicionales'},
				attrs={'class': 'form-control'})
		}

reisa/tickets/views.py
from datetime import datetime

from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_safe
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from braces.views import GroupRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required, login_required
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404

from inventario.models import Equipo
from polizas.models import Poliza
from usuarios.models import User
from reisa.utils import date_generator, filter_list

from .models import TicketConPoliza
from .forms import TicketPolizaCreateForm, TicketPolizaUpdateForm, TicketPolizaCloseForm, TicketPolizaCreatebyEncargadoForm
# Create your views here.

class TicketPolizaCreateView(SuccessMessageMixin, LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = TicketConPoliza
    form_class = TicketPolizaCreateForm
    template_name = "tickets/ticket_create_form.html"
    permission_required = 'tickets.add_ticketconpoliza'
    raise_exception = True
    success_url = reverse_lazy('tickets:list')
    success_message = "Ticket creado con éxito"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_designated_person:
            return redirect('tickets:create_by_encargado')
        return super(TicketPolizaCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        ticket = form.instance
        ticket.registrado_por = self.request.user
        return super(TicketPolizaCreateView, self).form_valid(form)


class TicketPolizaEditView(SuccessMessageMixin, LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = TicketConPoliza
    form_class = TicketPolizaUpdateForm
    template_name = "tickets/ticket_update_form.html"
    success_url = reverse_lazy('tickets:list')
    permission_required = 'tickets.change_ticketconpoliza'
    raise_exception = True
    success_message = "Ticket modificado con éxito"

    def get_context_data(self, **kwargs):
        context = super(TicketPolizaEditView, self).get_context_data(**kwargs)
        context['equipos'] = Equipo.objects.filter(id_poliza = self.object.poliza)
        return context


class TicketPolizaListView(LoginRequiredMixin, ListView):
    model = TicketConPoliza
    context_object_name = "tickets"
    template_name = "tickets/ticket_list.html"
    paginate_by = 8
    user_group = None
    user_groups = []

    def get_queryset(self):
        self.user_groups = list(self.request.user.groups.values_list('name', flat=True))
        if "Encargados" in self.user_groups:
            tickets = TicketConPoliza.objects.select_related('poliza', 'registrado_por', 'equipo').filter(poliza = self.request.user.poliza)

        elif "Soporte" in self.user_groups and not "Soporte Administrador" in self.user_groups:
            tickets = TicketConPoliza.objects.select_related('poliza', 'registrado_por', 'equipo', 'atendido_por').filter(atendido_por=self.request.user)
        else:
            tickets = TicketConPoliza.objects.select_related('poliza', 'registrado_por', 'equipo').all()

        if self.request.GET.get('poliza'):
            tickets = tickets.filter(poliza = self.request.GET.get('poliza'))

        return filter_list(tickets, self.request.GET).order_by('-created_at', 'status')

    def get_context_data(self, **kwargs):
        context = super(TicketPolizaListView, self).get_context_data(**kwargs)
        context['polizas'] = Poliza.objects.all()

        if "Encargados" in self.user_groups:
            context['equipos'] = Equipo.objects.filter(id_poliza=self.request.user.poliza)

        if self.request.GET.get('poliza'):
            context['equipos'] = Equipo.objects.filter(id_poliza = self.request.GET.get('poliza'))
            context['url_poliza'] = "poliza={0}&".format(self.request.GET.get('poliza'))

        if self.request.GET.get('equipo') != "" and self.request.GET.get('equipo') != None:
            context['url_equipo'] = "equipo={0}&".format(self.request.GET.get('equipo'))

        if 'created_at__gte' in self.request.GET and 'created_at__lt' in self.request.GET:
            context['url_gte'] = "created_at__gte={0}&".format(self.request.GET.get('created_at__gte'))
            context['url_lt'] = "created_at__lt={0}&".format(self.request.GET.get('created_at__lt'))
        if 'status__exact' in self.request.GET:
            context['url_status'] = "status__exact={0}&".format(self.request.GET.get('status__exact'))

        context['dates'] = date_generator()
        context['user_group'] = self.user_group
        return context


class TicketPolizaDetailView(LoginRequiredMixin, DetailView):
    model = TicketConPoliza
    context_object_name = "ticket"
    template_name = "tickets/ticket_detail.html"

@login_required
@require_safe
def autorizar_servicio(request, pk):
    ticket = get_object_or_404(TicketConPoliza, id=pk)
    if not ticket.is_complete():
        messages.error(request, "El ticket no ha sido atendido, no puedes autorizarlo aún.")
        return redirect(request.GET.get('next'))
    ticket.autorizacion_cliente = True
    if request.user.encargado.empresa.status == False:
        ticket.status = '4'
    else:
        ticket.status = '5'
    ticket.save()
    messages.success(request, "Ticket autorizado con éxito!")
    return redirect(request.GET.get('next'))

@login_required
def asignar_soporte(request, pk):
    if request.method == "POST":
        asignado = False
        antiguo_asignado = None
        usuario = get_object_or_404(User, username = request.POST.get('soporte'))
        ticket = get_object_or_404(TicketConPoliza, id = pk)
        if ticket.atendido_por:
            asignado = True
            antiguo_asignado = ticket.atendido_por
        fecha_asignada = request.POST.get('fecha_programada')
        ticket.atendido_por = usuario
        ticket.fecha_programada = datetime.strptime(fecha_asignada, "%d/%m/%Y").strftime('%Y-%m-%d')
        ticket.hora_aproximada = datetime.strptime(request.POST.get('hora_programada'), "%H:%M").time()
        ticket.status = '2'
        ticket.tipo_de_atencion = request.POST.get('tipo_atencion')
        ticket.save()
        enviar_email(request, ticket, asignado, antiguo_asignado)
        messages.success(request, 'Soporte asignado con éxito')
        return redirect(request.GET.get('next'))
    else:
        soportes = User.objects.filter(groups__name = 'Soporte')
        ticket = get_object_or_404(TicketConPoliza, id = pk)
        # Si el ticket no ha sido atendido
        if ticket.status == '1' or ticket.status == '2':
            return render(request, "tickets/ticket_assign_soporte.html", {'soportes': soportes, 'ticket': ticket})
        # Si el ticket ya fue atendido enviamos un mensaje de error
        messages.error(request, 'El tiket ya fue atendido, no se le puede asignar de nuevo un soporte.')
        return redirect(request.GET.get('next'))


def enviar_email(request, ticket, reasignado, antiguo_soporte):
    domain = request.build_absolute_uri('/')[:-1]
    template_html = render_to_string("emails/support_template.html", {'poliza': ticket.poliza, 'ticket': ticket, 'equipo': ticket.equipo, 'domain': domain})
    template_txt = render_to_string("emails/support_template.txt", {'poliza': ticket.poliza, 'ticket': ticket, 'equipo': ticket.equipo, 'domain': domain})
    if reasignado:
        template_cancel = render_to_string("emails/cancel_template.txt", {'ticket': ticket})
        send_mail('Soporte reasignado', template_cancel, 'soporte@reisa.mx', [antiguo_soporte.email])

    send_mail('Tienes un nuevo soporte', template_txt, 'soporte@reisa.mx', [ticket.atendido_por.email], html_message=template_html)

@login_required
def concluir_soporte(request, pk):
    ticket = get_object_or_404(TicketConPoliza, id = pk)
    if ticket.status != '3':
        messages.error(request, 'El ticket aún no se puede concluir en su status actual.')
        return redirect('tickets:list')
    if request.method == "POST":
        form = TicketPolizaCloseForm(request.POST, instance = ticket)
        if form.is_valid():
            form.instance.status = '3'
            form.instance.fecha_atencion = datetime.now()
            form.save()
            messages.success(request, 'Ticket concluido con éxito, gracias por tu excelente trabajo ^.^')
            return redirect(request.GET.get('next'))
        else:
            return render(request, "tickets/ticket_close_soporte.html", {'ticket': ticket, 'form': form})
    form = TicketPolizaCloseForm(instance = ticket)
    return render(request, "tickets/ticket_close_soporte.html", {'ticket': ticket, 'form': form})

@login_required
@permission_required('tickets.add_ticketconpoliza', raise_exception = True)
def crear_ticket_por_encargado(request):
    equipos = Equipo.objects.filter(id_poliza=request.user.poliza)
    if request.method == "POST":
        form = TicketPolizaCreatebyEncargadoForm(request.POST)
        form.instance.poliza = request.user.poliza
        if form.is_valid():
            form.instance.registrado_por = request.user
            form.save()
            messages.success(request, 'Ticket {form.instance.id} registrado con éxito')
            return redirect('tickets:list')
        else:
            return render(request, "tickets/ticket_create_encargado_form.html", {'form': form, 'equipos': equipos})
    form = TicketPolizaCreatebyEncargadoForm()
    return render(request, "tickets/ticket_create_encargado_form.html", {'form': form, 'equipos': equipos})


@login_required
def autorizar_cobro(request, pk):

reisa/templates/tickets/ticket_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Listado de Tickets{% endblock %}

{% block contenido %}

	<section class="content-header">
		<div class="row d-flex  align-items-center">
			<h2 class="col-xl-8 col-md-6">Tickets</h2>
			{% if "tickets.add_ticketconpoliza" in user.get_group_permissions %}
				<div class="actions col-xl-4 col-md-6 d-flex justify-content-end">
					{% if user.is_designated_person %}
						<a href="{% url 'tickets:create_by_encargado' %}" class="btn-action btn-green"><span class="fa fa-plus "></span>Crear Ticket</a>
					{% else %}
						<a href="{% url 'tickets:create_ticket' %}" class="btn-action btn-green"><span class="fa fa-plus "></span>Crear Ticket</a>
					{% endif %}
				</div>
			{% endif %}
		</div>
	</section>
	
	<section class="content">
		<div class="row">
			<div class="col-12">
				<div class="box">
					<div class="box-header with-border">
						<h4 class="box-title">Listado de tickets</h4>
						<!-- <h6 class="box-subtitle">Lista de pólizas registradas en el sistema</h6> -->
						{% include "messages.html" %}
					</div>
					<div class="box-body">
						<div class="row">
							<div class="col-lg-10 col-md-12">
								<table class="table table-hover table-striped table-responsive-md mt-0">
									<thead class="thead-dark">
										<tr>
											<th>FOLIO</th>
											<th>PÓLIZA</th>
											<th>EQUIPO</th>
											<th>FECHA DE CREACIÓN</th>
											<th>REGISTRADO POR</th>
											<th>STATUS</th>
											<th>AUTORIZACIÓN DEL ENCARGADO</th>
											<th>ACCIONES</th>
										</tr>
									</thead>
									<tbody>
										{% for ticket in tickets %}
											<tr>
												<td {% if ticket.status == '2' %}class='bg-orange'{% endif %} {% if ticket.status == '1' %}class='bg-red'{% endif %} {% if ticket.status == '3' %}class='bg-yellow'{% endif %}{% if ticket.status == '4' %}class='bg-blue'{% endif %}{% if ticket.status == '5' %}class='bg-green'{% endif %}>{{ ticket.id }}</td>
												<td>{{ ticket.poliza.nombre }}</td>
												<td>{{ ticket.equipo.id }}</td>
												<td>{{ ticket.created_at|date}}</td>
												<td>{{ ticket.registrado_por.first_name}}&nbsp;{{ticket.registrado_por.last_name}}</td>
												<td>{{ ticket.get_status_display }}</td>
												{% if ticket.autorizacion_cliente %}
													<td class="text-center"><span class="fa fa-check-circle text-green"></td>
												{% else %}
													<td class="text-center"><span class="fa fa-times-circle text-red"></span></td>
												{% endif %}
												<td>
													{% if perms.tickets.change_ticketconpoliza and not ticket.is_complete %}
														<a href="{% url 'tickets:update' ticket.id %}" title="Editar ticket"><span class="fa fa-pencil-alt text-yellow"></span></a>
													{% endif %}													
													{% if user_group.name == "Encargados" and not ticket.autorizacion_cliente and ticket.is_attended %}
														<a href="{% url 'tickets:autorizar' ticket.id %}?next={{request.get_full_path}}" title="Autorizar soporte"><span class="fa fa-check text-green"></span></a>
													{% endif %}
													{% if perms.tickets.add_soporte and not ticket.is_complete %}
														<a href="{% url 'tickets:asignar' ticket.id %}?next={{request.get_full_path}}" title="Asignar soporte"><span class="fa fa-user-plus text-blue"></span></a>
													{% endif %}
													{% if user_group.name == "Soporte" and not ticket.is_complete %}
														<a href="{% url 'tickets:concluir' ticket.id %}?next={{request.get_full_path}}" title="Concluir soporte"><span class="fa fa-check text-green"></span></a>
													{% endif %}
													{% if ticket.status == '4' and user_group.name == "Administración" %}
														<a href="{% url 'tickets:cobro' ticket.id %}?next={{request.get_full_path}}" title="Autorizar cobro"><span class="fa fa-dollar text-green"></span></a>
													{% endif %}
													<a href="{% url 'tickets:detail' ticket.id %}" title="Ver detalles"><span class="fa fa-eye text-purple"></span></a>
												</td>
											</tr>
										{% endfor %}
									</tbody>
								</table>
								{% if is_paginated %}
									<div class="row d-flex align-items-center">
										<div class="col-lg-6 col-md-12">
												Mostrando página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
										</div>
										<div class="col-lg-6 col-md-12">
											<ul class="pagination justify-content-end">
												{% if page_obj.has_previous %}
													<li class="page-item">
														<a href="{% url 'tickets:list' %}?page={{ page_obj.previous_page_number }}" class="page-link">Anterior</a>
													</li>
												{% endif %}
												{% for page in page_obj.paginator.page_range %}
													{% if page == page_obj.number %}
														<li class="page-item active">
															<a href="{% url 'tickets:list' %}?page={{ page }}" class="page-link">{{page}}</a>
														</li>
													{% else %}
														<li class="page-item">
															<a href="{% url 'tickets:list' %}?page={{ page }}" class="page-link">{{page}}</a>
														</li>
													{% endif %}
												{% endfor %}
												{% if page_obj.has_next %}
													<li class="page-item">
														<a href="{% url 'tickets:list' %}?page={{ page_obj.next_page_number }}" class="page-link">Siguiente</a>
													</li>
												{% endif %}
											</ul>
										</div>
									</div>
								{% endif %}
							</div>
							<div class="col-lg-2 col-sm-12">
									<form action="" method="GET">
											{% if user_group.name != "Encargados" %}
											<div class="filter">
												<span>Por poliza</span>
												<a href="?{{url_status}}{{url_gte}}{{url_lt}}">Todas las pólizas</a>
												<div class="row">
													<select name="poliza" id="id_poliza" class="custom-select col-9">
														<option value="">Seleccione una póliza</option>
														{% for poliza in polizas %}		
															{% if 'poliza' in request.GET and poliza.folio == request.GET.poliza %}
																<option value="{{poliza.folio}}" selected>{{poliza.nombre}}</option>
															{% else %}
																<option value="{{poliza.folio}}">{{poliza.nombre}}</option>
															{% endif %}
														{% endfor %}
													</select>
													<button class="col-2 btn btn-primary"><span class="fa fa-search"></span></button>
												</div>
											</div>
											{% endif %}
										{% if 'poliza' in request.GET or 'equipo' in request.GET or user_group.name == "Encargados"%}
											<div class="filter">
												<span>Por equipo</span>
												<a href="?{{url_poliza}}{{url_status}}{{url_gte}}{{url_lt}}">Todos los equipos</a>
												<div class="row">
													<select name="equipo" id="id_equipo" class="custom-select col-9">
														<option value="">Seleccione un equipo</option>
														{% for equipo in equipos %}		
															{% if 'equipo' in request.GET and equipo.id == request.GET.equipo %}
																<option value="{{equipo.id}}" selected>{{equipo.id}}</option>
															{% else %}
																<option value="{{equipo.id}}">{{equipo.id}}</option>
															{% endif %}
														{% endfor %}
													</select>
													<button class="btn btn-primary col-2"><span class="fa fa-search"></span></button>
												</div>
											</div>
										{% endif %}
										</form>
								<!-- FILTROS BASE -->
								<div class="filter">
									<span>Por status</span>
									<a href="{% url 'tickets:list' %}?{{url_poliza}}{{url_equipo}}{{url_gte}}{{url_lt}}">Todos</a>
									<a href="{% url 'tickets:list' %}?{{url_poliza}}{{url_equipo}}{{url_gte}}{{url_lt}}status__exact=1">Pendiente</a>
									<a href="{% url 'tickets:list' %}?{{url_poliza}}{{url_equipo}}{{url_gte}}{{url_lt}}status__exact=2">Asignado</a>
									<a href="{% url 'tickets:list' %}?{{url_poliza}}{{url_equipo}}{{url_gte}}{{url_lt}}status__exact=3">Atendido</a>
									<a href="{% url 'tickets:list' %}?{{url_poliza}}{{url_equipo}}{{url_gte}}{{url_lt}}status__exact=4">Sin cobro</a>
									<a href="{% url 'tickets:list' %}?{{url_poliza}}{{url_equipo}}{{url_gte}}{{url_lt}}status__exact=5">Completo</a>
								</div>
								<div class="filter">
									<span>Por fecha de creación</span>
									<a href="{% url 'tickets:list' %}?{{url_poliza}}{{url_equipo}}{{url_status}}">Cualquier fecha</a>
									<a href="{% url 'tickets:list' %}?{{url_poliza}}{{url_equipo}}{{url_status}}created_at__gte={{dates.now.0|date:'Y-m-d'}}&created_at__lt={{dates.now.1|date:'Y-m-d'}}">Hoy</a>
									<a href="{% url 'tickets:list' %}?{{url_poliza}}{{url_equipo}}{{url_status}}created_at__gte={{dates.last_7.0|date:'Y-m-d'}}&created_at__lt={{dates.last_7.1|date:'Y-m-d'}}">Últimos 7 días</a>
									<a href="{% url 'tickets:list' %}?{{url_poliza}}{{url_equipo}}{{url_status}}created_at__gte={{dates.this_month.0|date:'Y-m-d'}}&created_at__lt={{dates.this_month.1|date:'Y-m-d'}}">Este mes</a>
									<a href="{% url 'tickets:list' %}?{{url_poliza}}{{url_equipo}}{{url_status}}created_at__gte={{dates.this_year.0|date:'Y-m-d'}}&created_at__lt={{dates.this_year.1|date:'Y-m-d'}}">Este año</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	{% if is_paginated %}
		 <div class="pagination">
            	<span class="page-current">
                    Pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_previous %}
                    <a href="{% url 'polizas:list' %}?page={{ page_obj.previous_page_number }}" class="page_number bg-red"><span class="fa fa-chevron-left fa-inverse"></span></a>
                {% endif %}
                {% for page in page_obj.paginator.page_range %}
                	<div class="page_number">
            			<a href="{% url 'polizas:list' %}?page={{ page }}">{{page}}</a>
            		</div>
            	{% endfor %}
                {% if page_obj.has_next %}
                	<a href="{% url 'polizas:list' %}?page={{ page_obj.next_page_number }}" class="page_number bg-red"><span class="fa fa-chevron-right fa-inverse"></span></a>
                {% endif %}
        </div>
	{% endif %}

	{% if is_paginated %}
		 <div class="pagination">
            	<span class="page-current">
                    Pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_previous %}
                    <a href="{% url 'usuarios:list' %}?page={{ page_obj.previous_page_number }}" class="page_number bg-red"><span class="fa fa-chevron-left fa-inverse"></span></a>
                {% endif %}
                {% for page in page_obj.paginator.page_range %}
                	<div class="page_number">
            			<a href="{% url 'usuarios:list' %}?page={{ page }}">{{page}}</a>
            		</div>
            	{% endfor %}
                {% if page_obj.has_next %}
                	<a href="{% url 'usuarios:list' %}?page={{ page_obj.next_page_number }}" class="page_number bg-red"><span class="fa fa-chevron-right fa-inverse"></span></a>
                {% endif %}
        </div>
	{% endif %}
{% endblock %}