reisa/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from django.conf.urls import (
#     handler403
# )
from django.conf import settings
from django.conf.urls.static import static


import debug_toolbar

from reisa.views import home


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name="home"),
    url(r'^polizas/', include('polizas.urls', namespace="polizas")),
    url(r'^inventarios/', include('inventario.urls', namespace="inventarios")),
    url(r'^usuarios/', include('usuarios.urls', namespace="usuarios")),
    url(r'^tickets/', include('tickets.urls', namespace="tickets")),
    url(r'^froala_editor/', include('froala_editor.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reisa/usuarios/urls.py
from django.conf.urls import url
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete, LoginView, LogoutView

from .views import *


urlpatterns = [
    url(r'^password/reset/$',
    	password_reset,
    	{'post_reset_redirect' : 'usuarios:password_reset_done'},
    	name="password_reset"),
    url(r'^password/reset/done/$',
        password_reset_done,
        name="password_reset_done"),
    url(r'^password/reset/(?P<uidb36>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
        password_reset_confirm,
        {'post_reset_redirect': 'usuarios:password_success'},
        name="pasword_token"),
    url(r'^password/done/$', 
        password_reset_complete,
        name="password_success"),
    url(r'^login/$',
        LoginView.as_view(redirect_authenticated_user=True),
        name="login"),

    url(r'^logout/$',
        LogoutView.as_view(),
        {'next_page': '/'},
        name="logout"),

    url(r'^$',
        UsersListView.as_view(),
        name="list"),
    # Usuarios
    url(r'^create/$',
        UserCreateView.as_view(),
        name="create"),
    url(r'^update/(?P<pk>[\d]+)/$',
        UserUpdateView.as_view(),
        name="update")
]

reisa/usuarios/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser

from polizas.models import Poliza

class User(AbstractUser):
	telefono = models.CharField(max_length=50)
	is_designated_person = models.BooleanField(default=False)
	poliza = models.ForeignKey(Poliza, on_delete=models.CASCADE, blank=True, null=True)
	
	def __str__(self):
		return self.username

	class Meta:
		permissions = (("list_users", "Can list all the users"),)

# # Create your models here.
# class Encargado(models.Model):
# 	usuario = models.OneToOneField(User, on_delete=models.CASCADE)
# 	empresa = models.ForeignKey(Poliza, on_delete=models.CASCADE)

# 	def __str__(self):
# 		return "{0} - {1}".format(self.usuario.username, self.empresa.nombre)

reisa/usuarios/forms.py
from django.forms import ModelForm, TextInput, PasswordInput, CheckboxInput, SelectMultiple, Select
from django.contrib.auth.models import Group

from .models import User


class UserCreateForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['groups'].queryset = Group.objects.exclude(name="Encargados")

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'telefono',
                  'password', 'is_active', 'groups', 'poliza',
                  'is_designated_person']
        
        widgets = {
            'username': TextInput(attrs= {'placeholder': 'Nombre de usuario', 'class': 'form-control'}),
            'first_name': TextInput(attrs={'placeholder': 'Nombre', 'class': 'form-control'}),
            'last_name': TextInput(attrs={'placeholder': 'Apellidos', 'class': 'form-control'}),
            'email': TextInput(attrs={'placeholder': 'Email', 'class': 'form-control'}),
            'telefono': TextInput(attrs={'placeholder': 'Telefono', 'class': 'form-control'}),
            'password': PasswordInput(attrs={'placeholder': 'Contraseña', 'class': 'form-control'}),
            'is_active': CheckboxInput(attrs={'class': 'custom-control-input'}),
            'is_designated_person': CheckboxInput(attrs={'class': 'custom-control-input'}),
            'poliza': Select(attrs={'class': 'custom-select', 'disabled': 'true', 'required': 'true'}),
            'groups': SelectMultiple(attrs={'class': 'form-control', 'required': 'true'})
        }


class UserUpdateForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['groups'].queryset = Group.objects.exclude(name="Encargados")

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'telefono',
                  'is_active', 'groups', 'is_designated_person', 'poliza']
        widgets = {
            'username': TextInput(attrs= {'placeholder': 'Nombre de usuario', 'class': 'form-control'}),
            'first_name': TextInput(attrs={'placeholder': 'Nombre', 'class': 'form-control'}),
            'last_name': TextInput(attrs={'placeholder': 'Apellidos', 'class': 'form-control'}),
            'email': TextInput(attrs={'placeholder': 'Email', 'class': 'form-control'}),
            'telefono': TextInput(attrs={'placeholder': 'Telefono', 'class': 'form-control'}),
            'is_active': CheckboxInput(attrs={'class': 'custom-control-input'}),
            'is_designated_person': CheckboxInput(attrs={'class': 'custom-control-input'}),
            'poliza': Select(attrs={'class': 'custom-select', 'required': 'true'}),
            'groups': SelectMultiple(attrs={'class': 'form-control', 'required': 'true'})
        }

reisa/usuarios/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http.response import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import Group

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from .models import User
from .forms import UserCreateForm, UserUpdateForm

# Create your views here.
@login_required
def home(request, template_name="base.html"):
    return render(request, template_name, {})


class UserCreateView(SuccessMessageMixin, LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = User
    template_name = "usuarios/user_create_form.html"
    form_class = UserCreateForm
    success_url = reverse_lazy('usuarios:list')
    success_message = "Usuario %(username)s ha sido creado con éxito"
    permission_required = 'usuarios.add_user'
    raise_exception = True

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.set_password(form.cleaned_data["password"])
        self.object.save()
        if self.object.is_designated_person:
            encargados_group = Group.objects.get(name="Encargados")
            self.object.groups.add(encargados_group)
        else:
            self.object.groups.set(form.cleaned_data['groups'].all())
        self.object.save()
        return redirect(self.get_success_url())


class UserUpdateView(SuccessMessageMixin, LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = User
    template_name = "usuarios/user_update_form.html"
    form_class = UserUpdateForm
    success_url = reverse_lazy('usuarios:list')
    success_message = "Usuario %(username)s ha sido actualizado con éxito"
    permission_required = 'usuarios.change_user'
    raise_exception = True

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.groups.clear()
        if form.cleaned_data["is_designated_person"]:
            encargados_group = Group.objects.get(name="Encargados")
            self.object.groups.add(encargados_group)
        else:
            self.object.groups.set(form.cleaned_data["groups"].all())
        self.object.save()
        return redirect(self.get_success_url())


class UsersListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = User
    context_object_name = "users"
    template_name = "usuarios/users_list.html"
    permission_required = 'usuarios.list_users'
    raise_exception = True
    paginate_by = 8

    def get_queryset(self):
        users = User.objects.all().prefetch_related('groups', 'poliza').order_by('username')
        for k, vals in self.request.GET.lists():
            for v in vals:
                if k == "page":
                    continue
                users = users.filter(**{k:v})
        return users

    def get_context_data(self, **kwargs):
        context = super(UsersListView, self).get_context_data(**kwargs)
        if self.request.GET.get('is_active__exact'):
            context['status'] = "{0}={1}".format('is_active__exact', self.request.GET.get('is_active__exact'))
        if self.request.GET.get('groups__name__exact'):
            context['grupo'] = "{0}={1}".format('groups__name__exact', self.request.GET.get('groups__name__exact'))
        return context

reisa/templates/usuarios/encargado_create_form.html
{% extends 'base.html' %}

{% block title %}Crear nuevo usuario{% endblock %}

{% block contenido %}
	<section class="content-header">
		<div class="row d-flex  align-items-center">
			<h2 class="col-xl-8 col-md-6">Usuarios <span class="fa fa-angle-right"></span> Crear Encargado</h2>
			<div class="actions col-xl-4 col-md-6 d-flex justify-content-end">
					<a href="#" onclick="window.history.back()" class="btn-action btn-red"><span class="fa fa-angle-double-left"></span>Regresar</a>
			</div>
		</div>
	</section>

	<section class="content">
		<div class="row">
			<div class="col-12">
				<div class="box">
					<div class="box-header with-border">
						<h4 class="box-title">Crear nuevo encargado</h4>
						<!-- <h6 class="box-subtitle">Lista de pólizas registradas en el sistema</h6> -->
					</div>
					<div class="box-body">
						<form action="" method="post">
							{% csrf_token %}
							<div class="row">
								<div class="col-lg-6 col-md-12">
									<div class="form-group">
										{{form.username.label_tag}}
										{{form.username}}
										{% if form.username.errors %}
											<small class="text-red">
												{{form.username.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.first_name.label_tag}}
										{{form.first_name}}
										{% if form.first_name.errors %}
											<small class="text-red">
												{{form.first_name.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.last_name.label_tag}}
										{{form.last_name}}
										{% if form.last_name.errors %}
											<small class="text-red">
												{{form.last_name.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.email.label_tag}}
										{{form.email}}
										{% if form.email.errors %}
											<small class="text-red">
												{{form.email.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.telefono.label_tag}}
										{{form.telefono}}
										{% if form.telefono.errors %}
											<small class="text-red">
												{{form.telefono.errors.0}}
											</small>
										{% endif %}
									</div>
								</div>
								<div class="col-lg-6 col-md-12">
									<div class="form-group">
										{{form.password.label_tag}}
										{{form.password}}
										{% if form.password.errors %}
											<small class="text-red">
												{{form.password.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="custom-control custom-checkbox mb-2">
										{{form.is_active}}
										<label for="id_is_active" class="custom-control-label">Status</label>
									</div>
									<div class="form-group">
										<label for="poliza">Póliza:</label>
										<select name="poliza" id="id_poliza" class="custom-select">
											<option value="">Seleccione una póliza</option>
											{% for poliza in polizas %}
												<option value="{{ poliza.folio }}">{{poliza.nombre}}</option>
											{% endfor %}
										</select>
									</div>
									<div class="d-flex mt-3">
										<input type="submit" value="Registrar encargado" class="btn btn-primary">
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock contenido %}

reisa/templates/usuarios/encargado_update_form.html
{% extends 'base.html' %}

{% block title %}Crear nuevo usuario{% endblock %}

{% block contenido %}
	<section class="content-header">
		<div class="row d-flex  align-items-center">
			<h2 class="col-xl-8 col-md-6">Usuarios <span class="fa fa-angle-right"></span> Actualizar Encargado</h2>
			<div class="actions col-xl-4 col-md-6 d-flex justify-content-end">
					<a href="#" onclick="window.history.back()" class="btn-action btn-red"><span class="fa fa-angle-double-left"></span>Regresar</a>
			</div>
		</div>
	</section>

	<section class="content">
		<div class="row">
			<div class="col-12">
				<div class="box">
					<div class="box-header with-border">
						<h4 class="box-title">Actualizar encargado existente</h4>
						<!-- <h6 class="box-subtitle">Lista de pólizas registradas en el sistema</h6> -->
					</div>
					<div class="box-body">
						<form action="" method="post">
							{% csrf_token %}
							<div class="row">
								<div class="col-lg-6 col-md-12">
									<div class="form-group">
										{{form.username.label_tag}}
										{{form.username}}
										{% if form.username.errors %}
											<small class="text-red">
												{{form.username.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.first_name.label_tag}}
										{{form.first_name}}
										{% if form.first_name.errors %}
											<small class="text-red">
												{{form.first_name.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.last_name.label_tag}}
										{{form.last_name}}
										{% if form.last_name.errors %}
											<small class="text-red">
												{{form.last_name.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.email.label_tag}}
										{{form.email}}
										{% if form.email.errors %}
											<small class="text-red">
												{{form.email.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.telefono.label_tag}}
										{{form.telefono}}
										{% if form.telefono.errors %}
											<small class="text-red">
												{{form.telefono.errors.0}}
											</small>
										{% endif %}
									</div>
								</div>
								<div class="col-lg-6 col-md-12">
									<div class="form-group">
										{{form.password.label_tag}}
										{{form.password}}
										{% if form.password.errors %}
											<small class="text-red">
												{{form.password.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="custom-control custom-checkbox">
										{{form.is_active}}
										<label for="id_is_active" class="custom-control-label">Status</label>
									</div>
									<div class="form-group">
										{{form.groups.label_tag}}
										{{form.groups}}
									</div>
									<div class="form-group">
										<label for="poliza">Póliza:</label>
										<select name="poliza" id="id_poliza" class="custom-select">
											<option value="">Seleccione una póliza</option>
											{% for poliza in polizas %}
												{% if poliza.folio == poliza_actual %}
													<option value="{{ poliza.folio }}" selected>{{poliza.nombre}}</option>
												{% else %}
													<option value="{{ poliza.folio }}">{{poliza.nombre}}</option>
												{% endif %}
											{% endfor %}
										</select>
									</div>
									<div class="d-flex mt-3">
										<input type="submit" value="Actualizar encargado" class="btn btn-primary">
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock contenido %}

reisa/templates/usuarios/user_create_form.html
{% extends 'base.html' %}

{% block title %}Crear nuevo usuario{% endblock %}

{% block contenido %}
	<section class="content-header">
		<div class="row d-flex  align-items-center">
			<h2 class="col-xl-8 col-md-6">Usuarios <span class="fa fa-angle-right"></span> Crear</h2>
			<div class="actions col-xl-4 col-md-6 d-flex justify-content-end">
					<a href="#" onclick="window.history.back()" class="btn-action btn-red"><span class="fa fa-angle-double-left"></span>Regresar</a>
			</div>
		</div>
	</section>

	<section class="content">
		<div class="row">
			<div class="col-12">
				<div class="box">
					<div class="box-header with-border">
						<h4 class="box-title">Crear nuevo usuario</h4>
						<!-- <h6 class="box-subtitle">Lista de pólizas registradas en el sistema</h6> -->
					</div>
					<div class="box-body">
						<form action="" method="post">
							{% csrf_token %}
							<div class="row">
								<div class="col-lg-6 col-md-12">
									<div class="form-group">
										{{form.username.label_tag}}
										{{form.username}}
										{% if form.username.errors %}
											<small class="text-red">
												{{form.username.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.first_name.label_tag}}
										{{form.first_name}}
										{% if form.first_name.errors %}
											<small class="text-red">
												{{form.first_name.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.last_name.label_tag}}
										{{form.last_name}}
										{% if form.last_name.errors %}
											<small class="text-red">
												{{form.last_name.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.email.label_tag}}
										{{form.email}}
										{% if form.email.errors %}
											<small class="text-red">
												{{form.email.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.telefono.label_tag}}
										{{form.telefono}}
										{% if form.telefono.errors %}
											<small class="text-red">
												{{form.telefono.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.password.label_tag}}
										{{form.password}}
										{% if form.password.errors %}
											<small class="text-red">
												{{form.password.errors.0}}
											</small>
										{% endif %}
									</div>
								</div>
								<div class="col-lg-6 col-md-12">
									<div class="custom-control custom-checkbox">
										{{form.is_active}}
										<label for="id_is_active" class="custom-control-label">Status</label>
										{% if form.is_active.errors %}
											<small class="text-red">
												{{form.is_active.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="custom-control custom-checkbox mt-2">
										{{form.is_designated_person}}
										<label for="id_is_designated_person" class="custom-control-label">Encargado de póliza</label>
										{% if form.is_designated_person.errors %}
											<small class="text-red">
												{{form.is_designated_person.errors.0}}
											</small>
										{% endif %}
									</div>

									<div class="form-group mt-2">
										{{form.poliza.label_tag}}
										{{form.poliza}}
										{% if form.poliza.errors %}
											<small class="text-red">
												{{form.poliza.errors.0}}
											</small>
										{% endif %}
									</div>

									<div class="form-group">
										{{form.groups.label_tag}}
										{{form.groups}}
										{% if form.groups.errors %}
											<small class="text-red">
												{{form.groups.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="d-flex mt-3">
										<input type="submit" value="Registrar usuario" class="btn btn-primary">
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
	
{% endblock contenido %}

{% block js_extras %}
	<script>
		$("#id_is_designated_person").change(function() {
			if (this.checked) {
				$("#id_poliza").prop("disabled", false);
				$("#id_groups").prop("disabled", true);
			} else {
				$("#id_poliza").prop("disabled", true);
				$("#id_poliza").val("");
				$("#id_groups").prop("disabled", false);
			}
		})
	</script>
{% endblock js_extras %}

reisa/templates/usuarios/user_update_form.html
{% extends 'base.html' %}

{% block title %}Crear nuevo usuario{% endblock %}

{% block contenido %}
	<section class="content-header">
		<div class="row d-flex  align-items-center">
			<h2 class="col-xl-8 col-md-6">Usuarios <span class="fa fa-angle-right"></span> Actualizar</h2>
			<div class="actions col-xl-4 col-md-6 d-flex justify-content-end">
					<a href="#" onclick="window.history.back()" class="btn-action btn-red"><span class="fa fa-angle-double-left"></span>Regresar</a>
			</div>
		</div>
	</section>

	<section class="content">
		<div class="row">
			<div class="col-12">
				<div class="box">
					<div class="box-header with-border">
						<h4 class="box-title">Actualizar usuario</h4>
						<!-- <h6 class="box-subtitle">Lista de pólizas registradas en el sistema</h6> -->
					</div>
					<div class="box-body">
						<form action="" method="post">
							{% csrf_token %}
							<div class="row">
								<div class="col-lg-6 col-md-12">
									<div class="form-group">
										{{form.username.label_tag}}
										{{form.username}}
									</div>
									<div class="form-group">
										{{form.first_name.label_tag}}
										{{form.first_name}}
									</div>
									<div class="form-group">
										{{form.last_name.label_tag}}
										{{form.last_name}}
									</div>
									<div class="form-group">
										{{form.email.label_tag}}
										{{form.email}}
									</div>
									<div class="form-group">
										{{form.telefono.label_tag}}
										{{form.telefono}}
									</div>
									<div class="form-group">
										{{form.password.label_tag}}
										{{form.password}}
									</div>
								</div>
								<div class="col-lg-6 col-md-12">
									<div class="custom-control custom-checkbox">
										{{form.is_active}}
										<label for="id_is_active" class="custom-control-label">Status</label>
									</div>
									<div class="custom-control custom-checkbox mt-2">
										{{form.is_designated_person}}
										<label for="id_is_designated_person" class="custom-control-label">Encargado de póliza</label>
									</div>

									<div class="form-group mt-2">
										{{form.poliza.label_tag}}
										{{form.poliza}}
									</div>
									<div class="form-group">
										{{form.groups.label_tag}}
										{{form.groups}}
									</div>
									<div class="d-flex mt-3">
										<input type="submit" value="Actualizar usuario" class="btn btn-primary">
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
	
{% endblock contenido %}

{% block js_extras %}
	<script>
		$(document).ready(function() {
			{% if not form.instance.is_designated_person %}
				$("#id_poliza").prop("disabled", true);
			{% else %}	
				$("#id_groups").prop("disabled", true);
			{% endif %}
			$("#id_is_designated_person").change(function() {
				if (this.checked) {
					$("#id_poliza").prop("disabled", false);
					$("#id_groups").prop("disabled", true);
					$("#id_groups").val("3");
				} else {
					$("#id_poliza").prop("disabled", true);
					$("#id_groups").prop("disabled", false);
					$("#id_groups").val("");
				}
			});
		});

		
	</script>
{% endblock js_extras %}

reisa/templates/usuarios/users_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Listado de usuarios{% endblock %}	

{% block contenido %}

	<section class="content-header">
		<div class="row d-flex  align-items-center">
			<h2 class="col-xl-8 col-md-6">Usuarios</h2>
			{% if perms.usuarios.add_user %}
				<div class="actions col-xl-4 col-md-6 d-flex justify-content-end">
					<a href="{% url 'usuarios:create' %}" class="btn-action btn-green"><span class="fa fa-plus bg-dark-green"></span>Agregar usuario</a>
				</div>
			{% endif %}
		</div>
	</section>

	<section class="content">
		<div class="row">
			<div class="col-12">
				<div class="box">
					<div class="box-header with-border">
						<h4 class="box-title">Listado de usuarios</h4>
						<!-- <h6 class="box-subtitle">Lista de pólizas registradas en el sistema</h6> -->
						{% include 'messages.html' %}
					</div>
					<div class="box-body">
						<div class="row">
							<div class="col-lg-10 col-md-12">
								<table class="table table-hover table-striped table-responsive-md mt-0">
									<thead class="thead-dark">
										<tr>
											<th>USERNAME</th>
											<th>NOMBRE</th>
											<th>APELLIDOS</th>
											<th>EMAIL</th>
											<th>TÉLEFONO</th>
											<th>STATUS</th>
											<th>GRUPOS</th>
											<th>PÓLIZA</th>
											<th>ACCIONES</th>
										</tr>
									</thead>
									<tbody>
										{% for usuario in users %}
											<tr>
												<td>{{ usuario.username }}</td>
												<td>{{ usuario.first_name }}</td>
												<td>{{ usuario.last_name }}</td>
												<td>{{ usuario.email }}</td>
												<td>{{ usuario.telefono }}</td>
												{% if usuario.is_active %}
													<td><label class="label label-success">Activo</label></td>
												{% else %}
													<td><label class="label label-danger">Inactivo</label></td>
												{% endif %}
												<td>{{ usuario.groups.all.0}} {% if usuario.groups.all.1 %} | {{usuario.groups.all.1}}{% endif %}</td>
												<td>{{usuario.poliza.nombre|default:"N/A"}}</td>
												<td class="actions">
													{% if perms.usuarios.change_user %}
														<a href="{% url 'usuarios:update' usuario.id %}" title="Editar usuario"><span class="fa fa-pencil-alt text-yellow"></span></a>
													{% endif %}
												</td>
											</tr>
										{% endfor %}
									</tbody>
								</table>
								{% if is_paginated %}
									<div class="row d-flex align-items-center">
										<div class="col-lg-6 col-md-12">
												Mostrando página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
										</div>
										<div class="col-lg-6 col-md-12">
											<ul class="pagination justify-content-end">
												{% if page_obj.has_previous %}
													<li class="page-item">
														<a href="{% url 'usuarios:list' %}?page={{ page_obj.previous_page_number }}" class="page-link">Anterior</a>
													</li>
												{% endif %}
												{% for page in page_obj.paginator.page_range %}
													{% if page == page_obj.number %}
														<li class="page-item active">
															<a href="{% url 'usuarios:list' %}?page={{ page }}" class="page-link">{{page}}</a>
														</li>
													{% else %}
														<li class="page-item">
															<a href="{% url 'usuarios:list' %}?page={{ page }}" class="page-link">{{page}}</a>
														</li>
													{% endif %}
												{% endfor %}
												{% if page_obj.has_next %}
													<li class="page-item">
														<a href="{% url 'usuarios:list' %}?page={{ page_obj.next_page_number }}" class="page-link">Siguiente</a>
													</li>
												{% endif %}
											</ul>
										</div>
									</div>
								{% endif %}
							</div>
							<div class="col-lg-2 col-sm-12">
									<div class="filter">
										<span>Por estatus</span>
										<a href="{% url 'usuarios:list' %}?{{grupo}}" title="Ver todos">Todos/as</a>
										<a href="{% url 'usuarios:list' %}?{{grupo}}&is_active__exact=1" title="Filtrar activos">Activo</a>
										<a href="{% url 'usuarios:list' %}?{{grupo}}&is_active__exact=0" title="Filtrar inactivos">Inactivo</a>
									</div>
									<div class="filter">
										<span>Por grupo</span>
										<a href="{% url 'usuarios:list' %}?{{status}}" title="Ver todos">Todos/as</a>
										<a href="{% url 'usuarios:list' %}?{{status}}&groups__name__exact=Encargados" title="Filtrar encargados">Encargados</a>
										<a href="{% url 'usuarios:list' %}?{{status}}&groups__name__exact=Soporte" title="Filtrar soporte">Soporte</a>
										<a href="{% url 'usuarios:list' %}?{{status}}&groups__name__exact=Soporte Administrador" title="Filtrar Administración">Soporte Administrador</a>
										<a href="{% url 'usuarios:list' %}?{{status}}&groups__name__exact=Administración" title="Filtrar Administración">Administración</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock contenido %}