reisa/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from django.conf.urls import (
#     handler403
# )
from django.conf import settings
from django.conf.urls.static import static


import debug_toolbar

from reisa.views import home


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name="home"),
    url(r'^polizas/', include('polizas.urls', namespace="polizas")),
    url(r'^inventarios/', include('inventario.urls', namespace="inventarios")),
    url(r'^usuarios/', include('usuarios.urls', namespace="usuarios")),
    url(r'^tickets/', include('tickets.urls', namespace="tickets")),
    url(r'^froala_editor/', include('froala_editor.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reisa/inventario/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^$',
		inventario_poliza,
		name="list"),
	url(r'^(?P<poliza>[\w]+)/equipos/(?P<pk>[\w\s\d-]+)/$',
		EquipoDetailView.as_view(),
		name="detail"),
	url(r"^(?P<poliza>[\w]+)/equipos/$",
		EquipoListView.as_view(),
		name="equipos"
		),
	url(r"^(?P<poliza>[\w]+)/equipos/export$",
		export_xlsx,
		name="equipos_export"
		),
	url(r'^(?P<poliza>[\w]+)/equipos/create$',
		EquipoCreateView.as_view(),
		name="create"),
	url(r'^(?P<poliza>[\w]+)/equipos/create/multiple$',
		carga_equipos,
		name="create_massive"),
	url(r'^(?P<poliza>[\w]+)/equipos/update/(?P<pk>[\w\s\d-]+)/$',
		EquipoUpdateView.as_view(),
		name="update"),
	url(r'^(?P<poliza>[\w]+)/equipos/inhabilitar/(?P<pk>[\w\s\d-]+)/$',
		inhabilitar_equipo,
		name="inhabilitar"),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/licencias/$',
		LicenciaListView.as_view(),
		name="licencias_list"
		),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/licencias/create/$',
		LicenciaCreateView.as_view(),
		name="licencia_create"),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/licencias/update/(?P<pk>[\d]+)/$',
		LicenciaUpdateView.as_view(),
		name="licencia_update"),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/licencias/delete/(?P<pk>[\d]+)/$',
		LicenciaDeleteView.as_view(),
		name="licencia_delete"),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/historial/$',
		TicketListView.as_view(),
		name="tickets_list"),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/software/$',
		SoftwareListView.as_view(),
		name="software_list"),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/software/create/$',
		SoftwareCreateView.as_view(),
		name="software_create"),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/software/update/(?P<pk>[\d]+)/$',
		SoftwareUpdateView.as_view(),
		name="software_update"),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/software/delete/(?P<pk>[\d]+)/$',
		SoftwareDeleteView.as_view(),
		name="software_delete"),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/QRCode',
		show_qrcode,
		name="show_qrcode"),
	# URLS AJAX
	url(r'^equipos/$',
		equipos_por_poliza,
		name="equipos_list_ajax"),
	url(r'^(?P<poliza>\w+)/impresoras/create/$',
		ImpresoraCreateView.as_view(),
		name="impresoras_create"),
	url(r'^(?P<poliza>\w+)/impresoras/$',
		ImpresoraListView.as_view(),
		name="impresoras"),
	url(r'^(?P<poliza>\w+)/impresoras/(?P<pk>[\d]+)/update/$',
		ImpresoraUpdateView.as_view(),
		name="impresoras_update"),
	url(r'^(?P<poliza>\w+)/impresoras/(?P<pk>[\d]+)/delete/$',
		ImpresoraDeleteView.as_view(),
		name="impresoras_delete"),
	url(r'^(?P<poliza>\w+)/servidores/$',
		ServidorListView.as_view(),
		name="servidores"),
	url(r'^(?P<poliza>\w+)/servidores/create$',
		ServidorCreateView.as_view(),
		name="servidores_create"),
	url(r'^(?P<poliza>\w+)/servidores/(?P<pk>[\d]+)/$',
		ServidorDetailView.as_view(),
		name="servidores_detail"),
	url(r'^(?P<poliza>\w+)/servidores/(?P<pk>[\d]+)/update/$',
		ServidorUpdateView.as_view(),
		name="servidores_update"),
	url(r'^(?P<poliza>\w+)/servidores/(?P<pk>[\d]+)/delete/$',
		ServidorDeleteView.as_view(),
		name="servidores_delete"),
]

reisa/inventario/models.py
from django.utils import timezone
from django.urls import reverse
from django.core.files.uploadedfile import InMemoryUploadedFile
from qrcode import QRCode
from qrcode.constants import ERROR_CORRECT_L
from io import BytesIO
from django.db import models

from polizas.models import Poliza
from usuarios.models import User


class Equipo(models.Model):
    id = models.CharField(primary_key=True, max_length=50)
    marca = models.CharField(max_length=30, null=False)
    service_tag = models.CharField(max_length=50, null=False)
    sistema_operativo = models.CharField(max_length=50, null=False)
    disco_duro = models.CharField(max_length=20)
    ram = models.IntegerField(null=False)
    graficos = models.CharField(max_length=50, null=False)
    procesador = models.CharField(max_length=50, null=False)
    id_poliza = models.ForeignKey(Poliza, on_delete=models.CASCADE, null=False)
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    status = models.BooleanField(null=False, default=True)
    qrcode = models.ImageField(upload_to='qrcode', blank=True, null=True)
    username = models.CharField(max_length=60, blank=True, null=True)
    created_at = models.DateField(default=timezone.now)
    updated_at = models.DateField(auto_now=True)
    removed_at = models.DateField(default=None, null=True)

    class Meta:
        permissions = (
            ("detail_equipo", "Can see the equipo detail"),
            ("list_equipos", "Can list equipos"),
            ("export_equipos", "Can export xlsx file"))

    def get_absolute_url(self):
        host = "http://reisavirtual.ddns.net:81"
        path = reverse('inventarios:detail', args=[str(self.id_poliza.folio), str(self.id)])
        url = "{0}{1}".format(host, path)
        return url

    def generate_qrcode(self):
        qr = QRCode(
            version=1,
            error_correction=ERROR_CORRECT_L,
            box_size=14,
            border=2
        )
        print(self.get_absolute_url())
        qr.add_data(self.get_absolute_url())
        qr.make(fit=True)

        img = qr.make_image()

        buffer = BytesIO()
        img.save(buffer)

        filename = "computer-{0}.png".format(self.id)
        filebuffer = InMemoryUploadedFile(
            buffer, None, filename, 'image/png', buffer.tell(), None)
        self.qrcode.save(filename, filebuffer)

    def save(self, *args, **kwargs):
        super(Equipo, self).save(*args, **kwargs)

    def __str__(self):
        return self.id


class Licencia(models.Model):

    id = models.AutoField(primary_key=True)
    software = models.CharField(max_length=100, null=False)
    codigo = models.CharField(max_length=100, null=False)
    fecha_inicio = models.DateField(null=False)
    fecha_final = models.DateField(null=False)
    numero_licencia = models.IntegerField()
    id_equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)

    def __str__(self):
        return "{0} - {1}".format(self.id_equipo, self.software)


class Software(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50, null=False)
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)


class Impresora(models.Model):
    id = models.AutoField(primary_key=True)
    marca = models.CharField(max_length=50, blank=True, null=True)
    modelo = models.CharField(max_length=100)
    ip = models.GenericIPAddressField()
    poliza = models.ForeignKey(Poliza, on_delete=models.CASCADE)

    def __str__(self):
        return self.modelo

    class Meta:
        permissions = (
            ("list_impresora", "Can list impresoras"),
        )


class Servidor(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(primary_key=False, max_length=100)
    modelo = models.CharField(max_length=100)
    sistema_operativo = models.CharField(max_length=100, null=False)
    procesador = models.CharField(max_length=100, null=False)
    disco_duro = models.CharField(max_length=20)
    ram = models.IntegerField(null=False)
    poliza = models.ForeignKey(Poliza, on_delete=models.CASCADE)
    usuario = models.CharField(max_length=100, blank=True, null=True)
    password = models.CharField(max_length=150, blank=True, null=True)
    ip = models.GenericIPAddressField()
    puerto = models.CharField(max_length=30, blank=True, null=True)
    created_at = models.DateField(default=timezone.now)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.nombre

    class Meta:
        permissions = (
            ("detail_servidor", "Can see the servidor detail"),
            ("list_servidor", "Can list servidores"),
        )

reisa/inventario/forms.py
from django.forms import ModelForm, TextInput, NumberInput, DateInput
from django.utils.translation import ugettext_lazy as _


from .models import Equipo, Licencia, Software, Impresora, Servidor


class EquipoCreateForm(ModelForm):
	class Meta:
		model = Equipo
		exclude = ['id_poliza', 'usuario', 'removed_at', 'status', 'qrcode']
		widgets = {
			'id': TextInput(attrs= {'placeholder': 'Id del equipo', 'class': 'form-control'}),
			'marca': TextInput(attrs={'placeholder': 'Marca', 'class': 'form-control'}),
			'service_tag': TextInput(attrs={'placeholder': 'Service Tag', 'class': 'form-control'}),
			'sistema_operativo': TextInput(attrs={'placeholder': 'Sistema Operativo', 'class': 'form-control'}),
			'disco_duro': TextInput(attrs={'placeholder': 'Disco Duro', 'class': 'form-control'}),
			'ram': NumberInput(attrs={'placeholder': 'RAM', 'class': 'form-control'}),
			'graficos': TextInput(attrs={'placeholder': 'Gráficos', 'class': 'form-control'}),
			'procesador': TextInput(attrs={'placeholder': 'Procesador', 'class': 'form-control'}),
			'username': TextInput(attrs={'placeholder': 'Nombre de usuario', 'class': 'form-control'}),
			'created_at': DateInput(attrs={'placeholder': 'dd/mm/aaaa', 'class': 'datepicker', 'class': 'form-control'})
		}
		labels = {
			'created_at': _('Fecha de registro'),
		}

class EquipoUpdateForm(ModelForm):
	class Meta:
		model = Equipo
		exclude = ['id', 'id_poliza', 'usuario', 'removed_at', 'status', 'qrcode']
		widgets = {
			'marca': TextInput(attrs={'placeholder': 'Marca', 'class': 'form-control'}),
			'service_tag': TextInput(attrs={'placeholder': 'Service Tag', 'class': 'form-control'}),
			'sistema_operativo': TextInput(attrs={'placeholder': 'Sistema Operativo', 'class': 'form-control'}),
			'disco_duro': TextInput(attrs={'placeholder': 'Disco Duro', 'class': 'form-control'}),
			'ram': NumberInput(attrs={'placeholder': 'RAM', 'class': 'form-control'}),
			'graficos': TextInput(attrs={'placeholder': 'Gráficos', 'class': 'form-control'}),
			'procesador': TextInput(attrs={'placeholder': 'Procesador', 'class': 'form-control'}),
			'username': TextInput(attrs={'placeholder': 'Nombre de usuario', 'class': 'form-control'}),
			'created_at': DateInput(attrs={'placeholder': 'dd/mm/aaaa', 'class': 'datepicker', 'class': 'form-control'})
		}
		labels = {
			'created_at': _('Fecha de registro'),
		}


class LicenciaCreateForm(ModelForm):
	class Meta:
		model = Licencia
		exclude = ['id_equipo', 'usuario']
		widgets = {
			'software': TextInput(attrs= {'placeholder': 'Software', 'class': 'form-control'}),
			'codigo': TextInput(attrs={'placeholder': 'Código', 'class': 'form-control'}),
			'fecha_inicio': DateInput(attrs={'placeholder': 'Fecha de Inicio', 'class': 'datepicker form-control'}),
			'fecha_final': DateInput(attrs={'placeholder': 'Fecha de Fin', 'class': 'datepicker form-control'}),
			'numero_licencia': TextInput(attrs={'placeholder': 'Número de licencia', 'class': 'form-control'}),
		}
		labels = {
			'numero_licencia': _('Número de licencia'),
			'fecha_inicio': _('Fecha de inicio'),
			'fecha_final': _('Fecha de termino'),
		}

class SoftwareCreateForm(ModelForm):
	class Meta:
		model = Software
		fields = ['nombre']
		widgets = {
			'nombre': TextInput(attrs={'placeholder': 'Nombre del software', 'class': 'form-control'}),
		}
		labels = {
			'nombre': _('Nombre del software')
		}


class ImpresoraCreateForm(ModelForm):
	class Meta:
		model = Impresora
		exclude = ['id', 'poliza']
		widgets = {
			'marca': TextInput(attrs={'placeholder': 'Marca', 'class': 'form-control'}),
			'modelo': TextInput(attrs={'placeholder': 'Modelo', 'class': 'form-control'}),
			'ip': TextInput(attrs={'placeholder': 'IP', 'class': 'form-control'})
		}


class ServidorCreateForm(ModelForm):
	class Meta:
		model = Servidor
		exclude = ['id', 'poliza', 'created_at', 'updated_at']
		widgets = {
			'nombre': TextInput(attrs={'placeholder': 'Nombre del servidor', 'class': 'form-control'}),
			'modelo': TextInput(attrs={'placeholder': 'Modelo', 'class': 'form-control'}),
			'sistema_operativo': TextInput(attrs={'placeholder': 'Sistema Operativo', 'class': 'form-control'}),
			'disco_duro': TextInput(attrs={'placeholder': 'Disco Duro', 'class': 'form-control'}),
			'ram': NumberInput(attrs={'placeholder': 'RAM', 'class': 'form-control'}),
			'procesador': TextInput(attrs={'placeholder': 'Procesador', 'class': 'form-control'}),
			'usuario': TextInput(attrs={'placeholder': 'Usuario', 'class': 'form-control'}),
			'password': TextInput(attrs={'placeholder': 'Contraseña', 'class': 'form-control'}),
			'ip': TextInput(attrs={'placeholder': 'IP', 'class': 'form-control'}),
			'puerto': TextInput(attrs={'placeholder': 'Puerto', 'class': 'form-control'}),
			
		}
		labels = {
			'password': _('Contraseña')
		}

reisa/templates/inventario/carga_masiva_equipo.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Agregar nuevos equipos{% endblock %}


{% block contenido %}

	<section class="content-header">
		<div class="row d-flex  align-items-center">
			<h2 class="col-xl-8 col-md-6">Inventario <span class="fa fa-angle-right"></span> Carga masiva</h2>
			<div class="actions col-xl-4 col-md-6 d-flex justify-content-end">
					<a href="#" onclick="window.history.back()" class="btn-action btn-red"><span class="fa fa-angle-double-left"></span>Regresar</a>
			</div>
		</div>
	</section>
	
	<section class="content">
		<div class="row">
			<div class="col-12">
				<div class="box">
					<div class="box-header with-border">
						<h4 class="box-title">Carga masiva de equipos al inventario</h4>
						<h6 class="box-subtitle">Inventario de la póliza {{poliza.nombre}}</h6>
						{% include "messages.html" %}
					</div>
					<div class="box-body row d-flex justify-content-center">
						<form action="" method="POST" class="col-4" enctype="multipart/form-data">
							{% csrf_token %}
							<div class="row col-12">
								<div class="custom-file">
									<input type="file" name="json" class="custom-file-input" required accept="application/json" lang="es">
									<label for="json" class="custom-file-label">Archivo JSON:</label>
								</div>
							</div>
							<div class="row col-12 mt-3 d-flex justify-content-center">
								<input type="submit" class="btn btn-primary" value="Guardar equipos">
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock contenido %}

reisa/templates/inventario/carga_masiva_licencias.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Agregar nueva póliza{% endblock %}

{% block contenido %}
	<div class="title">
		<h3>Agregar nuevas licencias</h3>
	</div>

	{% include "messages.html" %}

	<form action="" method="POST" class="form-action" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="form-item">
			<label for="csv">Archivo CSV:</label>
			<input type="file" name="csv" required accept="text/csv">
		</div>
	<div class="button-container">
		<input type="submit" value="Guardar Licencias">	
	</div>
	</form>

{% endblock contenido %}

reisa/templates/inventario/equipo_create_form.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Crear nuevo equipo{% endblock %}

{% block styles_extras %}
	<link rel="stylesheet" href="{% static 'css/default.css' %}">
	<link rel="stylesheet" href="{% static 'css/default.date.css' %}">
{% endblock styles_extras %}

{% block contenido %}
	<section class="content-header">
		<div class="row d-flex  align-items-center">
			<h2 class="col-xl-8 col-md-6">Inventario <span class="fa fa-angle-right"></span> Registrar equipo</h2>
				<div class="actions col-xl-4 col-md-6 d-flex justify-content-end">
					<a href="#" onclick="window.history.back()" class="btn-action btn-red"><span class="fa fa-angle-double-left"></span>Regresar</a>
				</div>
		</div>
	</section>
	
	<section class="content">
		<div class="row">
			<div class="col-12">
				<div class="box">
					<div class="box-header with-border">
						<h4 class="box-title">Añadir equipo al inventario</h4>
						<!-- <h6 class="box-subtitle">Lista de pólizas registradas en el sistema</h6> -->
					</div>
					<div class="box-body">
						<form action="" method="post">
							{% csrf_token %}
							<div class="row">
								<div class="col-lg-6 col-md-12">
									<div class="form-group">
										{{form.id.label_tag}}
										{{form.id}}
										{% if form.id.errors %}
											<small class="text-red">
												{{form.id.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.marca.label_tag}}
										{{form.marca}}
										{% if form.marca.errors %}
											<small class="text-red">
												{{form.marca.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.service_tag.label_tag}}
										{{form.service_tag}}
										{% if form.service_tag.errors %}
											<small class="text-red">
												{{form.service_tag.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.sistema_operativo.label_tag}}
										{{form.sistema_operativo}}
										{% if form.sistema_operativo.errors %}
											<small class="text-red">
												{{form.sistema_operativo.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.disco_duro.label_tag}}
										{{form.disco_duro}}
										{% if form.disco_duro.errors %}
											<small class="text-red">
												{{form.disco_duro.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.ram.label_tag}}
										{{form.ram}}
										{% if form.ram.errors %}
											<small class="text-red">
												{{form.ram.errors.0}}
											</small>
										{% endif %}
									</div>
								</div>
								<div class="col-lg-6 col-md-12">
									<div class="form-group">
										{{form.graficos.label_tag}}
										{{form.graficos}}
										{% if form.graficos.errors %}
											<small class="text-red">
												{{form.graficos.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.procesador.label_tag}}
										{{form.procesador}}
										{% if form.procesador.errors %}
											<small class="text-red">
												{{form.procesador.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.username.label_tag}}
										{{form.username}}
										{% if form.username.errors %}
											<small class="text-red">
												{{form.username.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="form-group">
										{{form.created_at.label_tag}}
										{{form.created_at}}
										{% if form.created_at.errors %}
											<small class="text-red">
												{{form.created_at.errors.0}}
											</small>
										{% endif %}
									</div>
									<div class="d-flex mt-3">
										<input type="submit" value="Registrar equipo" class="btn btn-primary">
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock contenido %}

{% block js_extras %}
	<script src="{% static 'js/picker.js' %}"></script>
	<script src="{% static 'js/picker.date.js' %}"></script>
	<script>
	$('.datepicker').pickadate({
		format: 'dd/mm/yyyy',
		today: 'Hoy',
		clear: 'Limpiar',
		close: 'Cerrar',
		monthsFull: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
		monthsShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sept', 'Oct', 'Dic'],
		selectYears: true,
  		selectMonths: true,
  		weekdaysShort: ['Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab']
	});
	</script>
{% endblock js_extras %}

reisa/templates/inventario/licencias_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Listado de licencias{% endblock %}

{% block contenido %}

	<section class="content-header">
		<div class="row d-flex  align-items-center">
			<h2 class="col-xl-8 col-md-6">Inventario <span class="fa fa-angle-right"></span> Licencias</h2>
			<div class="actions col-xl-4 col-md-6 d-flex justify-content-end">
				{% if perms.inventario.add_licencia %}
					<a href="{% url 'inventarios:licencia_create' poliza.folio equipo.id %}" class="btn-action btn-green"><span class="fa fa-plus bg-dark-green"></span>Agregar licencia</a>
				{% endif %}
				<a href="#" onclick="window.history.back()" class="btn-action btn-red"><span class="fa fa-angle-double-left"></span> Regresar</a>
			</div>
		</div>
	</section>
	
	<section class="content">
		<div class="row">
			<div class="col-12">
				<div class="box">
					<div class="box-header with-border">
						<h4 class="box-title">Listado de licencias</h4>
						<h6 class="box-subtitle">Licencias instaladas en {{equipo.id}}</h6>
						{% include "messages.html" %}
					</div>
					<div class="box-body">
						<table class="table table-hover table-striped table-responsive-md mt-0">
							<thead class="thead-dark">
								<tr>
									<th>SOFTWARE</th>
									<th>SERIAL KEY</th>
									<th>FECHA DE INICIO</th>
									<th>FECHA DE FIN</th>
									<th>DIAS RESTANTES</th>
									<th># DE LICENCIA</th>
									<th>ACCIONES</th>
								</tr>
							</thead>
							<tbody>
								{% for licencia in licences %}
									<tr>
										<td>{{ licencia.software }}</td>
										<td>{{ licencia.codigo }}</td>
										<td>{{ licencia.fecha_inicio }}</td>
										<td>{{ licencia.fecha_final }}</td>
										<td>{{ licencia.fecha_final|timeuntil}}</td>
										<td>{{ licencia.numero_licencia }}</td>
										<td class="actions">
											{% if perms.inventario.change_licencia %}
												<a href="{% url 'inventarios:licencia_update' poliza.folio equipo.id licencia.id %}" title="Editar licencia"><span class="fa fa-pencil-alt text-yellow"></span></a>
											{% endif %}
											{% if perms.inventario.delete_licencia %}
												<a href="{% url 'inventarios:licencia_delete' poliza.folio equipo.id licencia.id %}" title="Eliminar licencia"><span class="fa fa-window-close text-red"></span></a>
											{% endif %}
										</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
						{% if is_paginated %}
							<div class="row d-flex align-items-center">
								<div class="col-lg-6 col-md-12">
										Mostrando página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
								</div>
								<div class="col-lg-6 col-md-12">
									<ul class="pagination justify-content-end">
										{% if page_obj.has_previous %}
											<li class="page-item">
												<a href="{% url 'inventarios:licencias_list' poliza.folio equipo.id %}?page={{ page_obj.previous_page_number }}" class="page-link">Anterior</a>
											</li>
										{% endif %}
										{% for page in page_obj.paginator.page_range %}
											{% if page == page_obj.number %}
												<li class="page-item active">
													<a href="{% url 'inventarios:licencias_list' poliza.folio equipo.id %}?page={{ page }}" class="page-link">{{page}}</a>
												</li>
											{% else %}
												<li class="page-item">
													<a href="{% url 'inventarios:licencias_list' poliza.folio equipo.id %}?page={{ page }}" class="page-link">{{page}}</a>
												</li>
											{% endif %}
										{% endfor %}
										{% if page_obj.has_next %}
											<li class="page-item">
												<a href="{% url 'inventarios:licencias_list' poliza.folio equipo.id %}?page={{ page_obj.next_page_number }}" class="page-link">Siguiente</a>
											</li>
										{% endif %}
									</ul>
								</div>
							</div>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock contenido %}

reisa/templates/inventario/show_qrcode.html
{% extends "base.html" %}

{% block title %}Código QR para {{equipo.id}} {% endblock %}

{% block contenido %}
    <section class="content-header">
        <div class="row d-flex  align-items-center">
            <h2 class="col-xl-8 col-md-6">Inventario <span class="fa fa-angle-right"></span> Equipo <span class="fa fa-angle-right"></span> QRCode</h2>
            <div class="actions col-xl-4 col-md-6 d-flex justify-content-end">
                <a href="#" onclick="window.history.back()" class="btn-action btn-red"><span class="fa fa-angle-double-left"></span> Regresar</a>
            </div>
        </div>
    </section>
    
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h4 class="box-title">Código QR para el equipo {{equipo.id}}</h4>
                        <!-- <h6 class="box-subtitle">Lista de pólizas registradas en el sistema</h6> -->
                    </div>
                    <div class="box-body">
                        <img src="{{equipo.qrcode.url}}" alt="Computer QR Code" class="mx-auto d-block" style="max-width: 450px; width: 100%;">
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock contenido %}