reisa/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from django.conf.urls import (
#     handler403
# )
from django.conf import settings
from django.conf.urls.static import static


import debug_toolbar

from reisa.views import home


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name="home"),
    url(r'^polizas/', include('polizas.urls', namespace="polizas")),
    url(r'^inventarios/', include('inventario.urls', namespace="inventarios")),
    url(r'^usuarios/', include('usuarios.urls', namespace="usuarios")),
    url(r'^tickets/', include('tickets.urls', namespace="tickets")),
    url(r'^froala_editor/', include('froala_editor.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reisa/inventario/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^$',
		inventario_poliza,
		name="list"),
	url(r'^(?P<poliza>[\w]+)/equipos/(?P<pk>[\w\s\d-]+)/$',
		EquipoDetailView.as_view(),
		name="detail"),
	url(r"^(?P<poliza>[\w]+)/equipos/$",
		EquipoListView.as_view(),
		name="equipos"
		),
	url(r"^(?P<poliza>[\w]+)/equipos/export$",
		export_xlsx,
		name="equipos_export"
		),
	url(r'^(?P<poliza>[\w]+)/equipos/create$',
		EquipoCreateView.as_view(),
		name="create"),
	url(r'^(?P<poliza>[\w]+)/equipos/create/multiple$',
		carga_equipos,
		name="create_massive"),
	url(r'^(?P<poliza>[\w]+)/equipos/update/(?P<pk>[\w\s\d-]+)/$',
		EquipoUpdateView.as_view(),
		name="update"),
	url(r'^(?P<poliza>[\w]+)/equipos/inhabilitar/(?P<pk>[\w\s\d-]+)/$',
		inhabilitar_equipo,
		name="inhabilitar"),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/licencias/$',
		LicenciaListView.as_view(),
		name="licencias_list"
		),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/licencias/create/$',
		LicenciaCreateView.as_view(),
		name="licencia_create"),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/licencias/update/(?P<pk>[\d]+)/$',
		LicenciaUpdateView.as_view(),
		name="licencia_update"),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/licencias/delete/(?P<pk>[\d]+)/$',
		LicenciaDeleteView.as_view(),
		name="licencia_delete"),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/historial/$',
		TicketListView.as_view(),
		name="tickets_list"),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/software/$',
		SoftwareListView.as_view(),
		name="software_list"),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/software/create/$',
		SoftwareCreateView.as_view(),
		name="software_create"),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/software/update/(?P<pk>[\d]+)/$',
		SoftwareUpdateView.as_view(),
		name="software_update"),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/software/delete/(?P<pk>[\d]+)/$',
		SoftwareDeleteView.as_view(),
		name="software_delete"),
	url(r'^(?P<poliza>\w+)/equipos/(?P<equipo>[\w\s\d-]+)/QRCode',
		show_qrcode,
		name="show_qrcode"),
	# URLS AJAX
	url(r'^equipos/$',
		equipos_por_poliza,
		name="equipos_list_ajax"),
	url(r'^(?P<poliza>\w+)/impresoras/create/$',
		ImpresoraCreateView.as_view(),
		name="impresoras_create"),
	url(r'^(?P<poliza>\w+)/impresoras/$',
		ImpresoraListView.as_view(),
		name="impresoras"),
	url(r'^(?P<poliza>\w+)/impresoras/(?P<pk>[\d]+)/update/$',
		ImpresoraUpdateView.as_view(),
		name="impresoras_update"),
	url(r'^(?P<poliza>\w+)/impresoras/(?P<pk>[\d]+)/delete/$',
		ImpresoraDeleteView.as_view(),
		name="impresoras_delete"),
	url(r'^(?P<poliza>\w+)/servidores/$',
		ServidorListView.as_view(),
		name="servidores"),
	url(r'^(?P<poliza>\w+)/servidores/create$',
		ServidorCreateView.as_view(),
		name="servidores_create"),
	url(r'^(?P<poliza>\w+)/servidores/(?P<pk>[\d]+)/$',
		ServidorDetailView.as_view(),
		name="servidores_detail"),
	url(r'^(?P<poliza>\w+)/servidores/(?P<pk>[\d]+)/update/$',
		ServidorUpdateView.as_view(),
		name="servidores_update"),
	url(r'^(?P<poliza>\w+)/servidores/(?P<pk>[\d]+)/delete/$',
		ServidorDeleteView.as_view(),
		name="servidores_delete"),
]

reisa/polizas/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(regex=r"^$", view=PolizaListView.as_view(), name="list"),
    url(r'^create/$', view=PolizaCreateView.as_view(), name="create"),
    url(r'^update/(?P<pk>[\w]+)/$', view=PolizaUpdateView.as_view(), name="update"),
    url(r'^(?P<pk>[\w]+)/$', PolizaDetailView.as_view(), name="detail"),
    url(r'^(?P<pk>[\w]+)/estadisticas/$', estadisticas_individuales, name="statistics"),
    url(r'^(?P<poliza>[\w]+)/contactos/create/$', view=ContactoCreateView.as_view(), name="contact_crate"),
    url(r'^(?P<poliza>[\w]+)/contactos/update/(?P<pk>[\d]+)/$', view=ContactoUpdateView.as_view(), name="contacto_update"),
    url(r'^(?P<poliza>[\w]+)/contactos/delete/(?P<pk>[\d]+)/$', view=ContactoDeleteView.as_view(), name="contacto_delete"),
    url(r'^(?P<poliza>[\w]+)/contactos', view=ContactoListView.as_view(), name="contacts"),
    url(r'^create/multiple/$', carga_polizas, name="create_multiple")
]

reisa/polizas/models.py
from django.db import models

# Create your models here.
class Poliza(models.Model):
	folio = models.CharField(max_length=20, null=False, primary_key=True)
	nombre = models.CharField(max_length=100, null=False)
	direccion = models.TextField(null=False)
	telefono = models.CharField(max_length=14, null=False)
	equipos_en_poliza = models.IntegerField(null=False)
	fecha_alta = models.DateField(null=False)
	ultima_revision_poliza = models.DateField(null=False)
	ultimo_servicio = models.DateField(null=False)
	status = models.BooleanField(default=True)

	class Meta:
		permissions = (('list_polizas', 'Can list all the polizas'),
						('list_equips', 'Can view the equips by poliza'))

	def save(self, *args, **kwargs):
		if self.folio is None or self.folio == "":
			nuevo_folio = "POL{0}".format(Poliza.objects.count() + 1)
			self.folio = nuevo_folio
		super(Poliza, self).save(*args, **kwargs)
	

	def __str__(self):
		return self.nombre


class Contacto(models.Model):
	id = models.AutoField(primary_key=True)
	nombre = models.CharField(max_length=50, null=False)
	apellido_paterno = models.CharField(max_length=50, null=False)
	apellido_materno = models.CharField(max_length=50, blank=True)
	telefono = models.CharField(max_length=50, null=False)
	email = models.EmailField(null=False)
	folio_poliza = models.ForeignKey(Poliza, on_delete=models.CASCADE)

	def __str__(self):
		return "{0} {1} {2}".format(self.nombre, self.apellido_paterno, self.apellido_materno)

reisa/polizas/forms.py
from django.forms import ModelForm, TextInput, DateInput, Textarea, CheckboxInput
from django.utils.translation import ugettext_lazy as _

from .models import Poliza, Contacto


class PolizaCreateForm(ModelForm):
	class Meta:
		model = Poliza
		fields = ['nombre','direccion', 'equipos_en_poliza', 'fecha_alta', 'ultima_revision_poliza', 'ultimo_servicio', 'status']
		widgets = {
			'nombre': TextInput(attrs={'placeholder': 'Nombre', 'class': 'form-control', 'autofocus': ''}),
			'direccion': Textarea(attrs={'placeholder': 'Dirección', 'class': 'form-control'}),
			'equipos_en_poliza': TextInput(attrs={'placeholder': 'Equipos en poliza', 'class': 'form-control'}),
			'fecha_alta': DateInput(attrs={'placeholder': 'dd/mm/aaaa', 'class': 'datepicker form-control'}),
			'ultima_revision_poliza': DateInput(attrs={'placeholder': 'dd/mm/aaaa', 'class': 'datepicker form-control'}),
			'ultimo_servicio': DateInput(attrs={'placeholder': 'dd/mm/aaaa', 'class': 'datepicker form-control'}),
			'status': CheckboxInput(attrs={'class': 'custom-control-input'})
		}
		labels = {
			'fecha_alta': _('Fecha de alta'),
			'ultima_revision_poliza': _('Última revisión de la poliza'),
			'ultimo_servicio': _('Último servicio anual'),
		}

class PolizaUpdateForm(ModelForm):
	class Meta:
		model = Poliza
		exclude = ('folio', 'telefono')
		widgets = {
			'nombre': TextInput(attrs={'placeholder': 'Nombre', 'class': 'form-control', 'autofocus': ''}),
			'direccion': Textarea(attrs={'placeholder': 'Dirección', 'class': 'form-control'}),
			'equipos_en_poliza': TextInput(attrs={'placeholder': 'Equipos en poliza', 'class': 'form-control'}),
			'fecha_alta': DateInput(attrs={'placeholder': 'dd/mm/aaaa', 'class': 'datepicker', 'class': 'form-control'}),
			'ultima_revision_poliza': DateInput(attrs={'placeholder': 'dd/mm/aaaa', 'class': 'datepicker form-control'}),
			'ultimo_servicio': DateInput(attrs={'placeholder': 'dd/mm/aaaa', 'class': 'datepicker form-control'}),
			'status': CheckboxInput(attrs={'class': 'custom-control-input'})
		}
		labels = {
			'fecha_alta': _('Fecha de alta'),
			'ultima_revision_poliza': _('Última revisión de la poliza'),
			'ultimo_servicio': _('Último servicio anual'),
		}

class ContactoCreateForm(ModelForm):
	class Meta:
		model = Contacto
		fields = ['nombre', 'apellido_paterno', 'apellido_materno', 'telefono', 'email']
		widgets = {
			'nombre': TextInput(attrs={'placeholder': 'Nombre', 'class': 'form-control'}),
			'apellido_paterno': TextInput(attrs={'placeholder': 'Apellido Paterno', 'class': 'form-control'}),
			'apellido_materno': TextInput(attrs={'placeholder': 'Apellido Materno', 'class': 'form-control'}),
			'telefono': TextInput(attrs={'placeholder': 'Télefono', 'class': 'form-control'}),
			'email': DateInput(attrs={'placeholder': 'Email', 'class': 'form-control'})
		}

reisa/polizas/views.py
import sys
from datetime import datetime

from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_safe
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import PermissionDenied
from django.db.models import Count, Q
from django.db.models.functions import TruncMonth
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from .models import Poliza, Contacto
from .forms import *
from reisa.utils import load_json
from tickets.models import TicketConPoliza
from inventario.models import Equipo


@login_required
@require_safe
def estadisticas_individuales(request, pk):
    # Si el usuario es encargado checamos que tenga la poliza asignada
    # si no mandamos 403
    if request.user.is_designated_person:
        folio = request.user.poliza.folio
        if folio != pk:
            raise PermissionDenied
    # Si no mostramos la poliza
    poliza = get_object_or_404(Poliza, folio=pk)
    # Tickets por mes 
    now = datetime.now()
    initial_date = now.replace(day=1, year=now.year-1)
    graph = TicketConPoliza.objects.filter(created_at__gte=initial_date, poliza=poliza).annotate(month=TruncMonth('created_at')).values('month').annotate(count=Count('id')).order_by('-month')
    print(graph)
    # Equipos dados de alta por año
    graph2 = Equipo.objects.filter(created_at__gte =initial_date, id_poliza=poliza).values('status').annotate(count=Count('status')).order_by('-status')

    return render(request, "polizas/polizas_statistics.html", {'poliza': poliza, 'graph': graph, 'graph2': graph2})


class PolizaListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Poliza
    context_object_name = "polizas"
    paginate_by = 8
    permission_required = 'polizas.list_polizas'
    raise_exception = True

    def get_queryset(self):
        return Poliza.objects.order_by('folio')


class PolizaDetailView(LoginRequiredMixin, DetailView):
    model = Poliza
    context_object_name = "poliza"

    def get_queryset(self):
        if self.request.user.is_designated_person:
            folio = self.request.user.poliza.folio
            if folio != self.kwargs['pk']:
                raise PermissionDenied
        return Poliza.objects.filter(folio=self.kwargs['pk']).annotate(equip_count=Count('equipo'))


class PolizaCreateView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, CreateView):
    model = Poliza
    template_name = "polizas/poliza_create_form.html"
    form_class = PolizaCreateForm
    success_url = reverse_lazy('polizas:list')
    permission_required = 'polizas.add_poliza'
    raise_exception = True
    success_message = "La póliza %(nombre)s ha sido creada con éxito"


class PolizaUpdateView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Poliza
    form_class = PolizaUpdateForm
    success_url = reverse_lazy('polizas:list')
    template_name = "polizas/poliza_update_form.html"
    permission_required = 'polizas.change_poliza'
    raise_exception = True
    success_message = "La poliza %(nombre)s ha sido modificada con éxito"


class ContactoCreateView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, CreateView):
    model = Contacto
    template_name = "polizas/contact_create_form.html"
    form_class = ContactoCreateForm
    permission_required = 'polizas.add_contacto'
    raise_exception = True
    success_message = "El contacto %(nombre)s ha sido creado con éxito"

    def form_valid(self, form):
        poliza = Poliza.objects.get(folio = self.kwargs['poliza'])
        poliza_id = poliza.folio
        form.instance.folio_poliza = poliza
        return super(ContactoCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('polizas:contacts', kwargs= {'poliza': self.kwargs['poliza']})


class ContactoUpdateView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Contacto
    template_name = "polizas/contact_create_form.html"
    form_class = ContactoCreateForm
    permission_required = 'polizas.change_contacto'
    raise_exception = True
    success_message = "El contacto %(nombre)s ha sido modificado con éxito"

    def get_success_url(self):
        return reverse_lazy('polizas:contacts', kwargs= {'poliza': self.kwargs['poliza']})


class ContactoDeleteView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Contacto
    template_name = "polizas/contact_delete_confirm.html"
    permission_required = 'polizas.delete_contacto'
    raise_exception = True
    success_message = "El contacto ha sido eliminado con éxito"

    def get_success_url(self):
        return reverse_lazy('polizas:contacts', kwargs= {'poliza': self.kwargs['poliza']})

class ContactoListView(LoginRequiredMixin, ListView):
    paginate_by = 8
    template_name = "polizas/contact_list.html"
    context_object_name = "contact_list"
    model = Contacto
    poliza = None
    
    def get_queryset(self):
        self.poliza = get_object_or_404(Poliza, folio = self.kwargs['poliza'])
        return Contacto.objects.filter(folio_poliza = self.poliza)

    def get_context_data(self, **kwargs):
        context = super(ContactoListView, self).get_context_data(**kwargs)
        context['poliza'] = self.poliza
        return context


@login_required
@permission_required('polizas.add_poliza', raise_exception=True)
def carga_polizas(request):
    if request.method == "POST":
        records = load_json(request, 'polizas:create_multiple')
        if records == -1:
            messages.error(request, "Formato de archivo invalido")
            return redirect('polizas:create_multiple')
        index = Poliza.objects.count()
        try:
             Poliza.objects.bulk_create([ Poliza(folio="POL{0}".format(index + i), nombre=line['nombre'].strip(), direccion=line['direccion'].strip(), telefono=line['telefono'].strip(), equipos_en_poliza=line['equipos'], fecha_alta=line['fecha_alta'].strip(), ultima_revision_poliza=line['ultima_revision_poliza'].strip(), ultimo_servicio=line['ultimo_servicio'].strip(), status=line['status']) for i, line in enumerate(records, start=1) ])
        except:
            messages.error(request, 'Ocurrio un error al almacenar las pólizas, revisa tu archivo e intenta de nuevo. {0}'.format(sys.exc_info()[1]))
            return redirect('polizas:create_multiple')
        
        return redirect('polizas:list')
        
    return render(request, "polizas/carga_masiva_form.html")

reisa/templates/polizas/carga_masiva_form.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Agregar pólizas{% endblock %}

{% block styles_extras %}
	<link rel="stylesheet" href="{% static 'css/sweetalert.css' %}">
{% endblock styles_extras %}

{% block contenido %}
	<section class="content-header">
		<div class="row d-flex  align-items-center">
			<h2 class="col-xl-8 col-md-6"><a href="{% url 'polizas:list' %}" class="text-secondary">Pólizas</a> <span class="fa fa-angle-right"></span> Carga Masiva</h2>
			<div class="actions col-xl-4 col-md-6 d-flex justify-content-end">
				<a href="#" onclick="window.history.back()" class="btn-action btn-red"><span class="fa fa-angle-double-left"></span>Regresar</a>
			</div>
		</div>
	</section>
	<section class="content">
		<div class="row">
			<div class="col-12">
				<div class="box">
					<div class="box-header with-border">
						<h4 class="box-title">Crear pólizas</h4>
						<h6 class="box-subtitle">Carga masiva de pólizas desde un archivo JSON</h6>
						{% include "messages.html" %}
					</div>
					<div class="box-body row d-flex justify-content-center">
						<form action="" method="POST" class="col-4" enctype="multipart/form-data">
							{% csrf_token %}
							<div class="row col-12">
								<div class="custom-file">
									<input type="file" name="json" class="custom-file-input" required accept="application/json" lang="es">
									<label for="csv" class="custom-file-label">Archivo JSON:</label>
								</div>
							</div>
							<div class="row col-12 mt-3 d-flex justify-content-center">
								<input type="submit" class="btn btn-primary" value="Guardar Pólizas">
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock contenido %}

{% block js_extras %}
	<script src="{% static 'js/sweetalert.min.js' %}"></script>
	{% include "messages.html" %}
{% endblock js_extras %}

reisa/templates/polizas/contact_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Listado de contactos{% endblock %}


{% block contenido %}
	<section class="content-header">
		<div class="row d-flex  align-items-center">
			<h2 class="col-xl-8 col-md-6"><a href="{% url 'polizas:list' %}" class="text-secondary">Pólizas</a> <span class="fa fa-angle-right"></span> Contactos</h2>
			<div class="actions col-xl-4 col-md-6 d-flex justify-content-end">
				{% if perms.polizas.add_contacto %}
					<a href="{% url 'polizas:contact_crate' poliza.folio %}" class="btn-action btn-green"><span class="fa fa-plus bg-dark-green"></span>Agregar contacto</a>
				{% endif %}
				<a href="#" onclick="window.history.back()" class="btn-action btn-red"><span class="fa fa-angle-double-left"></span>Regresar</a>
			</div>
		</div>
	</section>

	<section class="content">
		<div class="row">
			<div class="col-12">
				<div class="box">
					<div class="box-header with-border">
						<h4 class="box-title">Lista de contactos</h4>
						<h6 class="box-subtitle">Personas de referencia en {{poliza.nombre}}</h6>
						{% include "messages.html" %}
					</div>
					<div class="box-body">
						<table class="table table-hover table-striped table-responsive-md mt-0">
							<thead class="thead-dark">
								<tr>
									<th>Nombre</th>
									<th>Télefono</th>
									<th>Email</th>
									<th>Acciones</th>
								</tr>
							</thead>
							<tbody>
								{% for contacto in contact_list %}
									<tr>
										<td>{{contacto.nombre}}&nbsp;{{contacto.apellido_materno}}&nbsp;{{contacto.apellido_paterno}}</td>
										<td>{{contacto.telefono}}</td>
										<td>{{contacto.email}}</td>
										<td>
											{% if perms.polizas.change_contacto %}
												<a href="{% url 'polizas:contacto_update' poliza.folio contacto.id %}" title="Editar contacto"><span class="fa fa-pencil-alt text-yellow"></span></a>
											{% endif %}
											{% if perms.polizas.delete_contacto %}
												<a href="{% url 'polizas:contacto_delete' poliza.folio contacto.id %}" title="Eliminar contacto"><span class="fa fa-window-close text-red"></span></a>
											{% endif %}
										</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
						{% if is_paginated %}
							<div class="row d-flex align-items-center">
								<div class="col-lg-6 col-md-12">
										Mostrando página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
								</div>
								<div class="col-lg-6 col-md-12">
									<ul class="pagination justify-content-end">
										{% if page_obj.has_previous %}
											<li class="page-item">
												<a href="{% url 'polizas:contacts' poliza.folio %}?page={{ page_obj.previous_page_number }}" class="page-link">Anterior</a>
											</li>
										{% endif %}
										{% for page in page_obj.paginator.page_range %}
											{% if page == page_obj.number %}
												<li class="page-item active">
													<a href="{% url 'polizas:contacts' poliza.folio %}?page={{ page }}" class="page-link">{{page}}</a>
												</li>
											{% else %}
												<li class="page-item">
													<a href="{% url 'polizas:contacts' poliza.folio %}?page={{ page }}" class="page-link">{{page}}</a>
												</li>
											{% endif %}
										{% endfor %}
										{% if page_obj.has_next %}
											<li class="page-item">
												<a href="{% url 'polizas:contacts' poliza.folio %}?page={{ page_obj.next_page_number }}" class="page-link">Siguiente</a>
											</li>
										{% endif %}
									</ul>
								</div>
							</div>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

reisa/templates/polizas/poliza_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Listado de pólizas{% endblock %}

{% block contenido %}

	<section class="content-header">
		<div class="row d-flex  align-items-center">
			<h2 class="col-xl-8 col-md-6">Pólizas</h2>
			{% if perms.polizas.add_poliza %}
				<div class="actions col-xl-4 col-md-6 d-flex justify-content-end">
					<a href="{% url 'polizas:create' %}" class="btn-action btn-green"><span class="fa fa-plus"></span>Agregar póliza</a>
					<a href="{% url 'polizas:create_multiple' %}" class="btn-action btn-yellow"><span class="fa fa-plus"></span>Agregar varias</a>
				</div>
			{% endif %}
		</div>
	</section>

	<section class="content">
		<div class="row">
			<div class="col-12">
				<div class="box">
					<div class="box-header with-border">
						<h4 class="box-title">Listado de pólizas</h4>
						<!-- <h6 class="box-subtitle">Lista de pólizas registradas en el sistema</h6> -->
						{% include "messages.html" %}
					</div>
					<div class="box-body">
						<table class="table table-hover table-striped table-responsive-md mt-0">
							<thead class="thead-dark">
								<tr>
									<th>FOLIO</th>
									<th>NOMBRE</th>
									<th>DIRECCIÓN</th>
									<th>EQUIPOS EN PÓLIZA</th>
									<th>ÚLTIMO SERVICIO</th>
									<th>STATUS</th>
									<th class="sorttable_nosort">ACCIONES</th>
								</tr>
							</thead>
							<tbody>
								{% for poliza in polizas %}
									<tr>
										<td>{{ poliza.folio }}</td>
										<td>{{ poliza.nombre }}</td>
										<td width="400px">{{ poliza.direccion }}</td>
										<td>{{ poliza.equipos_en_poliza}}</td>
										<td>{{ poliza.ultimo_servicio|date }}</td>
										{% if poliza.status %}
											<td>
												<label class="label label-success">Activa</label>
											</td>
										{% else %}
											<td>
												<label class="label label-danger">Inactiva</label>
											</td>
										{% endif %}
										<td>
											{% if perms.polizas.change_poliza %}
												<a href="{% url 'polizas:update' poliza.folio %}" title="Editar póliza"><span class="fa fa-pencil-alt text-yellow"></span></a>
											{% endif %}
											<a href="{% url 'polizas:contacts' poliza.folio %}" title="Ver contactos"><span class="fa fa-address-book text-pink"></span></a>
											<a href="{% url 'polizas:statistics' poliza.folio %}" title="Ver estadisticas"><span class="fa fa-chart-line text-purple"></span></a>
											<a href="{% url 'polizas:detail' poliza.folio %}" title="Ver detalles"><span class="fa fa-eye text-blue"></span></a>
										</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
						{% if is_paginated %}
						<div class="row d-flex align-items-center">
							<div class="col-lg-6 col-md-12">
									Mostrando página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
							</div>
							<div class="col-lg-6 col-md-12">
								<ul class="pagination justify-content-end">
									{% if page_obj.has_previous %}
										<li class="page-item">
											<a href="{% url 'polizas:list' %}?page={{ page_obj.previous_page_number }}" class="page-link">Anterior</a>
										</li>
									{% endif %}
									{% for page in page_obj.paginator.page_range %}
										{% if page == page_obj.number %}
											<li class="page-item active">
												<a href="{% url 'polizas:list' %}?page={{ page }}" class="page-link">{{page}}</a>
											</li>
										{% else %}
											<li class="page-item">
												<a href="{% url 'polizas:list' %}?page={{ page }}" class="page-link">{{page}}</a>
											</li>
										{% endif %}
									{% endfor %}
									{% if page_obj.has_next %}
										<li class="page-item">
											<a href="{% url 'polizas:list' %}?page={{ page_obj.next_page_number }}" class="page-link">Siguiente</a>
										</li>
									{% endif %}
								</ul>
							</div>
						</div>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}